title: Introduction to Bioinformatics
description: Materials and notes for Masaryk University course DSIB01 Introduction to Bioinformatics taught in the fall semester 2021/2022
theme: jekyll-theme-tactile
